### ISSUE TITLE
Not working with core-2021.6.6

### ISSUE THREAD

**Issue by solidssss** [FreeTHX/wakeps4_on_bt-ha#1]
The log says:
Component error: wakeps4_on_bt - Integration 'wakeps4_on_bt' not found.
Platform error switch.wakeps4_on_bt - Integration 'wakeps4_on_bt' not found.
Platform error switch.wakeps4_on_bt - Integration 'wakeps4_on_bt' not found.

**Comment by FreeTHX** [comment]
Hi @solidssss 

[A version key is now required in manifest.json.](https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions)
I fixed it in 91b4c01fd6eb4090482a283b538aa2cd59dbbb52
