### ISSUE TITLE
Not working from Home Assistant 2022.7.0

### ISSUE THREAD

**Issue by flopon** [FreeTHX/wakeps4_on_bt-ha#2]
Due to switch to Python 3.10 from this release, this helpfull project does not work anymore.

**Comment by FreeTHX** [comment]
Hi @flopon 

I finaly took time to write on new version of [pywakeps4onbt](https://github.com/FreeTHX/pywakeps4onbt) without any external dependencies (pybluez was used for bluetooth and hci).
I made many tests and I now consider it stable.
Could you please confirm ?

**Comment by flopon** [comment]
Tested -> Working.

Thank you very much !

**Comment by tkdrob** [comment]
Which bluetooth adapters are you using? Both onboard and dongle show a log saying adapter does not yet support addr spoofing

**Comment by flopon** [comment]
Just checked my Amazon history, my BT dongle is the one below : 
https://www.xmpow.com/products/mpow-bh079a-usb-bluetooth-adapter-for-pc-1?_pos=4&_sid=2d30b89cb&_ss=r&_fid=d23eee6a9

BCM20702A0 chipset according to Home Assistant

**Comment by tkdrob** [comment]
Perfect, thanks. Looks like I ordered the right one 2 days ago. Thanks again.
